server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8   # json序列化时区配置
  data:
    redis:
      repositories:
        enabled: false

  redis:
    #数据库索引
    database: 0
    host: 118.89.143.27
    port: 6379
    password:
    #连接超时时间
    timeout: 10000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

