server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
#  profiles:
#    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.143.27:3306/blog_system?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true

    username: root
    password: 159357asd
    hikari:
      max-lifetime: 60000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 30 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      minimum-idle: 10

  data:
    redis:
      repositories:
        enabled: false

  redis:
    #数据库索引
    database: 0
    host: 118.89.143.27
    port: 6379
    password:
    #连接超时时间
    timeout: 10000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl